server:
  port: 8081
spring:
  application:
    name: next-gen
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/nextgen
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  profiles:
    active: default